on:
  workflow_dispatch:


jobs:
  delete-package-versions:
    name: Delete untagged images
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: snok/container-retention-policy@master
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ github.repository }}-quic-interop
          tag-selection: untagged
          cut-off: '1s'
          account_type: 'personal'
          dry-run: false
