on:
  workflow_dispatch:


jobs:
  delete-package-versions:
    name: Delete untagged images
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: snok/container-retention-policy@master
        with:
          org-name: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ github.repository }}-quic-interop
          untagged-only: true
          #tag-selection: untagged
          cut-off: '26 Aug 1999 22:52:55 GMT'
          account-type: 'personal'
          dry-run: false



   #         [ 'org-name', 'image-names', 'timestamp-to-use', 'cut-off',  'skip-tags', 'keep-at-least', 'filter-tags', 'filter-include-untagged', 'dry-run', 'token-type']
